/**
 * DecisionBar — action buttons shown below each assistant response.
 *
 * Adopt/Reject: logs decision with an optional reason.
 * Modify: collects feedback, re-runs the LLM with revised prompt, adds new
 *   response to the chat. The new response only allows Adopt/Reject (no
 *   further Modify), so we can measure modify→adopted vs modify→rejected.
 *
 * Reference: hacky-hours/02-design/BUSINESS_LOGIC.md § Decision Flow
 */

import { useState } from 'react'
import type { SessionResponse } from '../types/api'
import type { ChatMessage } from '../App'
import { sendDecision, sendMessage } from '../lib/api'
import { formatResponse } from './ChatPanel'

type Phase =
  | 'idle'
  | 'reason-adopt'    // optional reason for adopting
  | 'reason-reject'   // optional reason for rejecting
  | 'feedback'        // collecting feedback for Modify re-run
  | 'running'         // LLM re-run in progress
  | 'logged'          // final state after any decision

interface Props {
  response: SessionResponse
  activeCeoSlug: string
  question: string                  // the user message that produced this response
  isModifiedResponse?: boolean      // true = was generated by a Modify re-run (no further Modify)
  slackConfigured?: boolean         // hide Announce button when no Slack is set up
  onAnnounce: (prefillMessage: string, archetype_slug: string) => void
  onMessage: (msg: ChatMessage) => void  // adds a new message to the chat
  onDecision?: (decision: 'adopted' | 'rejected' | 'modified', modification?: string) => void
}

export function DecisionBar({
  response,
  activeCeoSlug,
  question,
  isModifiedResponse = false,
  slackConfigured = false,
  onAnnounce,
  onMessage,
  onDecision,
}: Props) {
  const [phase, setPhase] = useState<Phase>('idle')
  const [reasonText, setReasonText] = useState('')
  const [feedbackText, setFeedbackText] = useState('')
  const [runError, setRunError] = useState<string | null>(null)

  async function logDecision(
    decision: string,
    opts: { modification?: string; reason?: string; isModification?: boolean } = {}
  ) {
    try {
      await sendDecision({
        archetype_slug: activeCeoSlug,
        question,
        position: response.position,
        confidence: response.confidence,
        ambition_level: response.ambition_level,
        decision,
        modification: opts.modification,
        reason: opts.reason,
        is_modification: opts.isModification ?? isModifiedResponse,
      })
    } catch {
      // best-effort
    }
  }

  async function handleAdopt() {
    const reason = reasonText.trim() || undefined
    await logDecision('adopted', { reason })
    onDecision?.('adopted')
    setPhase('logged')
  }

  async function handleReject() {
    const reason = reasonText.trim() || undefined
    await logDecision('rejected', { reason })
    onDecision?.('rejected')
    setPhase('logged')
  }

  async function handleModifyRun() {
    const feedback = feedbackText.trim()
    if (!feedback) return

    setPhase('running')
    setRunError(null)

    try {
      // Log the modification decision first
      await logDecision('modified', { modification: feedback })
      onDecision?.('modified', feedback)

      // Re-run the LLM with the revision context
      const revised = await sendMessage({
        message: question,
        archetype_slug: activeCeoSlug,
        modification_context: {
          original_position: response.position,
          feedback,
        },
      })

      // Add the revised response as a new chat message (Modify not allowed on revisions)
      onMessage({
        role: 'assistant',
        content: formatResponse(revised),
        response: revised,
        timestamp: new Date().toISOString(),
        isModifiedResponse: true,
      })

      setPhase('logged')
    } catch (e: unknown) {
      setRunError(e instanceof Error ? e.message : 'Revision failed')
      setPhase('feedback')
    }
  }

  function handleAnnounce() {
    // Extract all <announce>…</announce> blocks and join them.
    // The LLM may produce multiple blocks (e.g. one per channel tone).
    const matches = [...response.position.matchAll(/<announce>([\s\S]*?)<\/announce>/gi)]
    const prefill = matches.length > 0
      ? matches.map(m => m[1].trim()).join('\n\n')
      : response.position
    onAnnounce(prefill, activeCeoSlug)
  }

  // ---- Render ----

  if (phase === 'logged') {
    return (
      <div className="mt-1 pl-1 font-mono text-[10px] text-[#444466]">
        ✓ logged to decisions.md
      </div>
    )
  }

  if (phase === 'running') {
    return (
      <div className="mt-2 pl-1 font-mono text-[10px] text-[#8888AA] animate-pulse">
        Revising…
      </div>
    )
  }

  if (phase === 'reason-adopt' || phase === 'reason-reject') {
    const isAdopt = phase === 'reason-adopt'
    const color = isAdopt ? '#7FFF00' : '#FF2D78'
    return (
      <div className="mt-2 flex flex-col gap-1">
        <textarea
          value={reasonText}
          onChange={(e) => setReasonText(e.target.value)}
          placeholder={`Reason for ${isAdopt ? 'adopting' : 'rejecting'} (optional)`}
          rows={2}
          autoFocus
          className="w-full bg-[#0A0A0F] rounded px-2 py-1 font-mono text-[10px] text-[#F0F0FF] placeholder:text-[#8888AA] resize-none focus:outline-none transition-colors"
          style={{ border: `1px solid ${color}44` }}
          onKeyDown={(e) => { if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); void (isAdopt ? handleAdopt() : handleReject()) } }}
        />
        <div className="flex gap-1">
          <button
            onClick={() => void (isAdopt ? handleAdopt() : handleReject())}
            className="px-2 py-0.5 font-mono text-[10px] rounded border transition-colors"
            style={{ borderColor: `${color}88`, color }}
          >
            {isAdopt ? '✓ Adopt' : '✗ Reject'}
          </button>
          <button
            onClick={() => { setPhase('idle'); setReasonText('') }}
            className="px-2 py-0.5 font-mono text-[10px] rounded border border-[#2A2A44] text-[#8888AA] hover:text-[#F0F0FF] transition-colors"
          >
            Cancel
          </button>
        </div>
      </div>
    )
  }

  if (phase === 'feedback') {
    return (
      <div className="mt-2 flex flex-col gap-1">
        <textarea
          value={feedbackText}
          onChange={(e) => setFeedbackText(e.target.value)}
          placeholder="What should be different? The CEO will revise based on this…"
          rows={2}
          autoFocus
          className="w-full bg-[#0A0A0F] border border-[#FFE600]/40 rounded px-2 py-1 font-mono text-[10px] text-[#F0F0FF] placeholder:text-[#8888AA] resize-none focus:outline-none focus:border-[#FFE600]"
        />
        {runError && (
          <p className="font-mono text-[10px] text-[#FF2D78]">{runError}</p>
        )}
        <div className="flex gap-1">
          <button
            onClick={() => void handleModifyRun()}
            disabled={!feedbackText.trim()}
            className="px-2 py-0.5 font-mono text-[10px] rounded border border-[#FFE600]/50 text-[#FFE600] hover:border-[#FFE600] transition-colors disabled:opacity-40"
          >
            Re-run ⚡
          </button>
          <button
            onClick={() => { setPhase('idle'); setFeedbackText(''); setRunError(null) }}
            className="px-2 py-0.5 font-mono text-[10px] rounded border border-[#2A2A44] text-[#8888AA] hover:text-[#F0F0FF] transition-colors"
          >
            Cancel
          </button>
        </div>
      </div>
    )
  }

  // idle
  return (
    <div className="mt-2 flex gap-1 flex-wrap">
      <button
        onClick={() => setPhase('reason-adopt')}
        className="px-2 py-0.5 font-mono text-[10px] rounded border border-[#7FFF00]/50 text-[#7FFF00] hover:border-[#7FFF00] transition-colors"
        aria-label="Adopt this position"
      >
        ✓ Adopt
      </button>
      <button
        onClick={() => setPhase('reason-reject')}
        className="px-2 py-0.5 font-mono text-[10px] rounded border border-[#FF2D78]/50 text-[#FF2D78] hover:border-[#FF2D78] transition-colors"
        aria-label="Reject this position"
      >
        ✗ Reject
      </button>
      {!isModifiedResponse && (
        <button
          onClick={() => setPhase('feedback')}
          className="px-2 py-0.5 font-mono text-[10px] rounded border border-[#FFE600]/50 text-[#FFE600] hover:border-[#FFE600] transition-colors"
          aria-label="Revise this position"
        >
          ~ Modify
        </button>
      )}
      {slackConfigured && (
        <button
          onClick={handleAnnounce}
          className="px-2 py-0.5 font-mono text-[10px] rounded border border-[#00F5FF]/50 text-[#00F5FF] hover:border-[#00F5FF] transition-colors"
          aria-label="Announce to Slack"
        >
          ↗ Announce
        </button>
      )}
    </div>
  )
}
